### ISSUE TITLE
libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

### ISSUE THREAD

**Issue by www2171668** [HorizonRobotics/alf#1050]
Hello. I want to use SocialRobot env. But when I run the sample in SocialRobot as 'python3 test_simple_navigation.py'. It prints ImportError: /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates. Of course, the problem comes when I use alf with SocailRobot env. Do you know how to deal with it? Thank you.

My gazebo is 9.16.0.

Traceback (most recent call last):
File "test_simple_navigation.py", line 5, in
import social_bot
File "/home/huang/Project/HIDIO/SocialRobot/python/social_bot/init.py", line 66, in
from . import pygazebo
ImportError: /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

**Comment by www2171668** [comment]
My gazebo is 9.19.0.

**Comment by www2171668** [comment]
get the method in 
http://blog.sina.com.cn/s/blog_54dd80920102v5js.html
and
https://www.it610.com/article/1188145227341340672.htm
