### ISSUE TITLE
map_structure() fails in a SAC + HER setting

### ISSUE THREAD

**Issue by JakobThumm** [HorizonRobotics/alf#1106]
Hi,

I'm trying to run SAC together with HER.
Unfortunately, I'm getting an error
```
E1203 17:38:06.614589 140193157813440 nest.py:54] map_structure() fails for (Experience(step_type=tensor([[0, 1],
        [0, 1],
        [0, 1],
        ...,
        [1, 1],
        [1, 1],
        [1, 1]], device='cuda:0', dtype=torch.int32), reward=tensor([[ 0., -1.],
        [ 0., -1.],
        [ 0., -1.],
        ...,
        [-1., -1.],
        [-1., -1.],
        [-1., -1.]], device='cuda:0'), discount=tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        ...,
        [1., 1.],
        [1., 1.],
        [1., 1.]], device='cuda:0'), observation=OrderedDict([('achieved_goal', tensor([[[-1.2300,  0.5380,  0.0699],
         [-1.2300,  0.5380,  0.0712]],

        [[-0.9312, -0.2614,  0.0699],
         [-0.9312, -0.2614,  0.0712]],

        [[-0.3025,  0.9560,  0.0699],
         [-0.3025,  0.9560,  0.0712]],

        ...,

        [[-0.2939, -0.9577,  0.0729],
         [-0.2939, -0.9577,  0.0729]],

        [[ 1.2256, -0.0098,  0.0729],
         [ 1.2256, -0.0098,  0.0729]],

        [[-0.8353, -0.3085,  0.0729],
         [-0.8353, -0.3085,  0.0729]]], device='cuda:0')), ('desired_goal', tensor([[[ 0.5009,  1.5851,  0.0030],
         [ 0.5009,  1.5851,  0.0030]],

        [[-1.0657,  1.5558,  0.0030],
         [-1.0657,  1.5558,  0.0030]],

        [[ 0.1514,  0.4314,  0.0030],
         [ 0.1514,  0.4314,  0.0030]],

        ...,

        [[-1.6355,  0.0183,  0.0030],
         [-1.6355,  0.0183,  0.0030]],

        [[-1.3232, -0.4962,  0.0030],
         [-1.3232, -0.4962,  0.0030]],

        [[ 0.0062,  1.4117,  0.0030],
         [ 0.0062,  1.4117,  0.0030]]], device='cuda:0')), ('observation', tensor([[[-1.0521, -2.2437,  0.7548,  ...,  0.7562, -0.2540, -0.9146],
         [-0.8848, -2.1284,  0.7866,  ...,  1.0303, -0.2652,  1.7044]],

        [[-1.0521, -2.2437,  0.7548,  ...,  0.7562, -0.2540, -0.9146],
         [-0.8848, -2.1284,  0.7866,  ...,  1.0303, -0.2652,  1.7044]],

        [[-1.0521, -2.2437,  0.7548,  ...,  0.7562, -0.2540, -0.9146],
         [-0.8848, -2.1284,  0.7866,  ...,  1.0303, -0.2652,  1.7044]],

        ...,

        [[-0.9265,  0.9635, -1.2113,  ..., -0.6329, -0.2418, -0.9099],
         [-1.0448,  0.9826, -1.3067,  ..., -0.5111, -0.2485, -0.9086]],

        [[-0.9265,  0.9635, -1.2113,  ..., -0.6329, -0.2418, -0.9099],
         [-1.0448,  0.9826, -1.3067,  ..., -0.5111, -0.2485, -0.9086]],

        [[-0.9265,  0.9635, -1.2113,  ..., -0.6329, -0.2418, -0.9099],
         [-1.0448,  0.9826, -1.3067,  ..., -0.5111, -0.2485, -0.9086]]],
       device='cuda:0'))]), prev_action=tensor([[[ 0.,  0.,  0.,  0.],
         [ 1.,  1., -1., -1.]],

        [[ 0.,  0.,  0.,  0.],
         [ 1.,  1., -1., -1.]],

        [[ 0.,  0.,  0.,  0.],
         [ 1.,  1., -1., -1.]],

        ...,

        [[ 1.,  1., -1., -1.],
         [ 1.,  1., -1., -1.]],

        [[ 1.,  1., -1., -1.],
         [ 1.,  1., -1., -1.]],

        [[ 1.,  1., -1., -1.],
         [ 1.,  1., -1., -1.]]], device='cuda:0'), env_id=tensor([[ 0,  0],
        [ 1,  1],
        [ 2,  2],
        ...,
        [17, 17],
        [18, 18],
        [19, 19]], device='cuda:0', dtype=torch.int32), action=tensor([[[ 1.,  1., -1., -1.],
         [ 1.,  1., -1., -1.]],

        [[ 1.,  1., -1., -1.],
         [ 1.,  1., -1., -1.]],

        [[ 1.,  1., -1., -1.],
         [ 1.,  1., -1., -1.]],

        ...,

        [[ 1.,  1., -1., -1.],
         [ 1.,  1., -1., -1.]],

        [[ 1.,  1., -1., -1.],
         [ 1.,  1., -1., -1.]],

        [[ 1.,  1., -1., -1.],
         [ 1.,  1., -1., -1.]]], device='cuda:0'), rollout_info=AgentInfo(rl=SacInfo(reward=(), step_type=(), discount=(), action=tensor([[[ 1.,  1., -1., -1.],
         [ 1.,  1., -1., -1.]],

        [[ 1.,  1., -1., -1.],
         [ 1.,  1., -1., -1.]],

        [[ 1.,  1., -1., -1.],
         [ 1.,  1., -1., -1.]],

        ...,

        [[ 1.,  1., -1., -1.],
         [ 1.,  1., -1., -1.]],

        [[ 1.,  1., -1., -1.],
         [ 1.,  1., -1., -1.]],

        [[ 1.,  1., -1., -1.],
         [ 1.,  1., -1., -1.]]], device='cuda:0'), action_distribution=TransformedDistribution(), actor=(), critic=(), alpha=(), log_pi=()), irm=(), goal_generator=(), entropy_target=(), repr=(), rw=(), rewards=()), state=AgentState(rl=SacState(action=SacActionState(actor_network=(), critic=()), actor=(), critic=SacCriticState(critics=(), target_critics=())), irm=(), goal_generator=(), repr=(), rw=()), batch_info=BatchInfo(env_ids=tensor([ 0,  1,  2,  ..., 17, 18, 19], device='cuda:0'), positions=tensor([  0,   0,   0,  ..., 498, 498, 498], device='cuda:0'), importance_weights=(), replay_buffer=()), replay_buffer=(), rollout_info_field=()),). Error message: ''TransformedDistribution' object has no attribute 'device''. The paths in nests are (['action', 'batch_info.env_ids', 'batch_info.positions', 'discount', 'env_id', 'observation.achieved_goal', 'observation.desired_goal', 'observation.observation', 'prev_action', 'reward', 'rollout_info.rl.action', 'rollout_info.rl.action_distribution', 'step_type'],).
```

To reproduce, use this `gin` file:
```
include 'sac_fetchpush.gin'

import alf.nest.utils
suite_robotics.load.concat_desired_goal=False
actor/ActorDistributionNetwork.preprocessing_combiner=@NestConcat()
critic/CriticNetwork.observation_preprocessing_combiner=@NestConcat()
critic/CriticNetwork.action_preprocessing_combiner=@NestConcat()

ReplayBuffer.keep_episodic_info=True
HindsightExperienceTransformer.her_proportion=0.8
TrainerConfig.data_transformer_ctor=[@ObservationNormalizer, @HindsightExperienceTransformer]
```

and run 
`python -m alf.bin.train --gin_file 'her_fetchpush_sac.gin' --root_dir /tmp/alf/her_fetchpush`

Is HER not supported for `ActorDistributionNetwork`s? Or is my gin file missing something?

Thanks,

Jakob

**Comment by hnyu** [comment]
Hi @JakobThumm , can you provide the complete stack trace?

**Comment by hnyu** [comment]
I was able to reproduce the error using the provided gin file:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/haonanyu/alf/alf/bin/train.py", line 234, in <module>
    app.run(main)
  File "/home/haonanyu/venv3.8/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/haonanyu/venv3.8/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/haonanyu/alf/alf/bin/train.py", line 202, in main
    training_worker(
  File "/home/haonanyu/alf/alf/bin/train.py", line 177, in training_worker
    raise e
  File "/home/haonanyu/alf/alf/bin/train.py", line 171, in training_worker
    _train(root_dir, rank, world_size)
  File "/home/haonanyu/alf/alf/bin/train.py", line 140, in _train
    trainer.train()
  File "/home/haonanyu/alf/alf/trainers/policy_trainer.py", line 170, in train
    common.run_under_record_context(
  File "/home/haonanyu/alf/alf/utils/common.py", line 286, in run_under_record_context
    func()
  File "/home/haonanyu/alf/alf/trainers/policy_trainer.py", line 433, in _train
    train_steps = self._algorithm.train_iter()
  File "/home/haonanyu/alf/alf/algorithms/rl_algorithm.py", line 619, in train_iter
    return self._train_iter_off_policy()
  File "/home/haonanyu/alf/alf/algorithms/rl_algorithm.py", line 654, in _train_iter_off_policy
    steps = self.train_from_replay_buffer(update_global_counter=True)
  File "/home/haonanyu/alf/alf/utils/common.py", line 959, in _func
    ret = func(*args, **kwargs)
  File "/home/haonanyu/alf/alf/algorithms/algorithm.py", line 1174, in train_from_replay_buffer
    return self._train_experience(
  File "/home/haonanyu/alf/alf/algorithms/algorithm.py", line 1199, in _train_experience
    experience = self.transform_experience(experience)
  File "/home/haonanyu/alf/alf/algorithms/algorithm.py", line 337, in transform_experience
    return self._data_transformer.transform_experience(experience)
  File "/home/haonanyu/alf/alf/algorithms/data_transformer.py", line 157, in transform_experience
    experience = trans.transform_experience(experience)
  File "/home/haonanyu/alf/alf/algorithms/data_transformer.py", line 755, in transform_experience
    experience = convert_device(experience)
  File "/home/haonanyu/alf/alf/nest/utils.py", line 275, in convert_device
    return nest.map_structure(_convert_cpu, nests)
  File "/home/haonanyu/alf/alf/nest/nest.py", line 55, in map_structure
    raise e
  File "/home/haonanyu/alf/alf/nest/nest.py", line 49, in map_structure
    return cnest.map_structure(func, *nests)
  File "/home/haonanyu/alf/alf/nest/utils.py", line 264, in _convert_cpu
    if tensor.device.type != 'cpu':
AttributeError: 'TransformedDistribution' object has no attribute 'device'
```

So far it seems to me that `TransformedDistribution` was stored in a replay buffer without extracting its parameters first, and `convert_device()` is called on the entire experience in `HindsightExperienceTransformer`. @le-horizon Can you take a look?

**Comment by hnyu** [comment]
Hi @JakobThumm , a temporary fix would be to comment out the `action_distribution`
``` python
return AlgStep(
            output=action,
            state=new_state,
            info=SacInfo(action=action,
                         #action_distribution=action_dist
                         ))
```
in the return result of SAC's `rollout_step()` function.

**Comment by le-horizon** [comment]
Hi @JakobThumm , Thanks for reporting the issue.

I've created a fix https://github.com/HorizonRobotics/alf/commit/b3e4fd06c8aebb7d40f75f503bd602f5dc42c2ec
and testing it in our mujoco docker.  (Seeing some issue with environment reward mismatching recalculated/relabeled reward.  It does not seem to be related to this fix.)

Hope this fixes the issue for you.

Thanks for the quick triaging @hnyu !

**Comment by le-horizon** [comment]
The other problem was due to hindsight data transformer being added after other transformations.

PR #1107 fixes that as well, but you need to change your gin config as well @JakobThumm .
`TrainerConfig.data_transformer_ctor=[**@HindsightExperienceTransformer**, @ObservationNormalizer]`

**Comment by JakobThumm** [comment]
Hi @hnyu and @le-horizon ,

thank you for your quick response and fix.
Sorry for my delayed response as I was away over the weekend.

Your fixes work great and I can now play around with SAC and HER. Thanks!

Best,

Jakob
