### ISSUE TITLE
ppo_rnd_mrevenge.gin failed

### ISSUE THREAD

**Issue by 1nF0rmed** [HorizonRobotics/alf#718]
When test with ppo_rnd_mrevenge

```
python -m alf.bin.train --gin_file=ppo_rnd_mrevenge.gin --root_dir=~/ppo
```

got error message as shown below:

```
I1110 23:18:39.304719 139673910417216 parallel_environment.py:92] Spawning all processes.
I1110 23:18:55.285165 139673910417216 parallel_environment.py:99] All processes started.
I1110 23:19:02.194811 139673910417216 policy_trainer.py:309] observation_spec=BoundedTensorSpec(shape=(1, 84, 84), dtype=torch.uint8, minimum=array(0, dtype=uint8), maximum=array(255, dtype=uint8))
I1110 23:19:02.195204 139673910417216 policy_trainer.py:311] action_spec=BoundedTensorSpec(shape=(), dtype=torch.int64, minimum=array(0), maximum=array(17))
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/inf0rmed/git/alf/alf/bin/train.py", line 96, in <module>
    app.run(main)
  File "/home/inf0rmed/git/alf/env/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/inf0rmed/git/alf/env/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/inf0rmed/git/alf/alf/bin/train.py", line 88, in main
    train_eval(FLAGS.ml_type, FLAGS.root_dir)
  File "/home/inf0rmed/git/alf/env/lib/python3.8/site-packages/gin/config.py", line 1142, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/inf0rmed/git/alf/env/lib/python3.8/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/home/inf0rmed/git/alf/env/lib/python3.8/site-packages/gin/config.py", line 1119, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/inf0rmed/git/alf/alf/bin/train.py", line 75, in train_eval
    trainer = policy_trainer.RLTrainer(trainer_conf)
  File "/home/inf0rmed/git/alf/alf/trainers/policy_trainer.py", line 320, in __init__
    self._algorithm = self._algorithm_ctor(
  File "/home/inf0rmed/git/alf/env/lib/python3.8/site-packages/gin/config.py", line 350, in scoping_wrapper
    return fn(*args, **kwargs)
  File "/home/inf0rmed/git/alf/env/lib/python3.8/site-packages/gin/config.py", line 1142, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/inf0rmed/git/alf/env/lib/python3.8/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/home/inf0rmed/git/alf/env/lib/python3.8/site-packages/gin/config.py", line 1119, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/inf0rmed/git/alf/alf/algorithms/agent.py", line 126, in __init__
    rl_algorithm = rl_algorithm_cls(
  File "/home/inf0rmed/git/alf/env/lib/python3.8/site-packages/gin/config.py", line 350, in scoping_wrapper
    return fn(*args, **kwargs)
  File "/home/inf0rmed/git/alf/env/lib/python3.8/site-packages/gin/config.py", line 1142, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/inf0rmed/git/alf/env/lib/python3.8/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/home/inf0rmed/git/alf/env/lib/python3.8/site-packages/gin/config.py", line 1119, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/inf0rmed/git/alf/env/lib/python3.8/site-packages/gin/config.py", line 1142, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/inf0rmed/git/alf/env/lib/python3.8/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/home/inf0rmed/git/alf/env/lib/python3.8/site-packages/gin/config.py", line 1119, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/inf0rmed/git/alf/alf/algorithms/actor_critic_algorithm.py", line 77, in __init__
    actor_network = actor_network_ctor(
  File "/home/inf0rmed/git/alf/env/lib/python3.8/site-packages/gin/config.py", line 1142, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/inf0rmed/git/alf/env/lib/python3.8/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/home/inf0rmed/git/alf/env/lib/python3.8/site-packages/gin/config.py", line 1119, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/inf0rmed/git/alf/alf/networks/network.py", line 87, in _capture_init
    init(self, **kwargs)
  File "/home/inf0rmed/git/alf/alf/networks/actor_distribution_networks.py", line 91, in __init__
    self._encoding_net = EncodingNetwork(
  File "/home/inf0rmed/git/alf/env/lib/python3.8/site-packages/gin/config.py", line 1142, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/inf0rmed/git/alf/env/lib/python3.8/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/home/inf0rmed/git/alf/env/lib/python3.8/site-packages/gin/config.py", line 1119, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/inf0rmed/git/alf/alf/networks/network.py", line 87, in _capture_init
    init(self, **kwargs)
  File "/home/inf0rmed/git/alf/alf/networks/encoding_networks.py", line 599, in __init__
    assert self._processed_input_tensor_spec.ndim == 1, \
AssertionError: The input shape (4, 84, 84) should be like (N,)!
  In call to configurable 'EncodingNetwork' (<class 'alf.networks.encoding_networks.EncodingNetwork'>)
  In call to configurable 'ActorDistributionNetwork' (<class 'alf.networks.actor_distribution_networks.ActorDistributionNetwork'>)
  In call to configurable 'ActorCriticAlgorithm' (<class 'alf.algorithms.actor_critic_algorithm.ActorCriticAlgorithm'>)
  In call to configurable 'PPOAlgorithm' (<class 'alf.algorithms.ppo_algorithm.PPOAlgorithm'>)
  In call to configurable 'Agent' (<class 'alf.algorithms.agent.Agent'>)
  In call to configurable 'train_eval' (<function train_eval at 0x7f07e65ab0d0>)
```

**Comment by emailweixu** [comment]
Sorry for the late reply. I just tried this on my machine. There is no problem at all. However, I am using python 3.7, while you are using python 3.8. We never tested our code using python 3.8.

**Comment by 1nF0rmed** [comment]
Hey! sorry for late reply. I tried it with Python 3.7, I was able to replicate the results.
